name: build

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          submodules: true

      - name: Initialise environment for ${{ github.ref }}
        shell: pwsh
        run: |
          $out = git rev-list d4a9001b.. --count
          echo "VER=1.$out" | Out-File -FilePath $Env:GITHUB_ENV -Encoding utf-8 -Append

      - name: "Log environment info: v${{ env.VER }}"
        run: |
          echo VER: %VER%
          echo dotnet --version:
          dotnet --version

      - name: Install dotnet
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '7.x'

      - name: dotnet restore
        run: dotnet restore

      - name: dotnet publish
        run: |
          dotnet publish --configuration Release --no-restore -p:Version=${{env.VER}} -p:FileVersion=${{env.VER}} -p:AssemblyVersion=${{env.VER}}

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: RomanKeys-v${{env.VER}}
          path: |
            Builds/Release-publish/
          if-no-files-found: error

      - name: "Tag: ver/main/v${{ env.VER }}"
        if: ${{ success() && github.ref == 'refs/heads/main' }}
        uses: mathieudutour/github-tag-action@fcfbdceb3093f6d85a3b194740f8c6cec632f4e2
        continue-on-error: true
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          custom_tag: ver/main/${{ env.VER }}
          tag_prefix:
